apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncd-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncd-backend
  template:
    metadata:
      labels:
        app: syncd-backend
    spec:
      containers:
        - name: syncd-backend
          image: "dlckswn334/sync-d-backend:f63c6de0e7d38daec3f71372462a28142d381954"
          ports:
            - containerPort: 8080
