apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncd-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncd-backend
  template:
    metadata:
      labels:
        app: syncd-backend
    spec:
      containers:
        - name: syncd-backend
          image: "dlckswn334/sync-d-backend:fa353c5883c8105b47362d37d6b1b1c8e927334f"
          ports:
            - containerPort: 8080
