apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncd-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncd-backend
  template:
    metadata:
      labels:
        app: syncd-backend
    spec:
      containers:
        - name: syncd-backend
          image: "dlckswn334/sync-d-backend:1372eb5383ae1d223a0e0360d57bed515be1cb72"
          ports:
            - containerPort: 8080
