apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncd-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncd-backend
  template:
    metadata:
      labels:
        app: syncd-backend
    spec:
      containers:
      - name: syncd-backend
        image: jayoh712/syncd:latest
        ports:
        - containerPort: 8080