apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncd-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncd-backend
  template:
    metadata:
      labels:
        app: syncd-backend
    spec:
      containers:
        - name: syncd-backend
          image: "dlckswn334/sync-d-backend:a69c650ee6e829bb060f8c374d17e17ae6ea3022"
          ports:
            - containerPort: 8080
