apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncd-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncd-backend
  template:
    metadata:
      labels:
        app: syncd-backend
    spec:
      containers:
        - name: syncd-backend
          image: "dlckswn334/sync-d-backend:f376f6c3e7d52a8cb67c998d0cd990c19eb71b8a"
          ports:
            - containerPort: 8080
