apiVersion: v1
kind: Service
metadata:
  name: sonaqube-external
  namespace: ingress-nginx
spec:
  type: ExternalName
  externalName: sonarqube-sonarqube.sonarqube.svc.cluster.local
  ports:
    - port: 9000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonaqube-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - sonaqube.dev.i-dear.org
      secretName: wildcard-dev-idear-cert
  rules:
    - host: sonaqube.dev.i-dear.org
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: sonaqube-external
                port:
                  number: 9000