apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: idear-cert
  namespace: ingress-nginx
spec:
  dnsNames:
    - 'i-dear.org'
  issuerRef:
    kind: ClusterIssuer
    name: le-wildcard-issuer
  secretName: idear-cert

# ---

# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: idear-wildcard-cert
#   namespace: ingress-nginx
# spec:
#   dnsNames:
#     - '*.i-dear.org'
#   issuerRef:
#     kind: ClusterIssuer
#     name: le-wildcard-issuer
#   secretName: wildcard-idear-cert

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: idear-dev-wildcard-cert
  namespace: ingress-nginx
spec:
  dnsNames:
    - '*.dev.i-dear.org'
  issuerRef:
    kind: ClusterIssuer
    name: le-wildcard-issuer
  secretName: wildcard-dev-idear-cert
